export const homeCopy = {
  ar: {
    metaTitle: "اشتراكاتك الرقمية في الجزائر",
    metaDescription:
      "اختر اشتراكك الرقمي من Tiger Store. أسعار بالدينار، دفع عبر BaridiMob أو Binance أو RedotPay، وخطوات واضحة من الطلب إلى التفعيل.",
    eyebrow: "اشتراكات رقمية · الجزائر",
    headline: "اشتراكك القادم،",
    headlineAccent: "بكل وضوح.",
    intro:
      "من Snapchat Plus إلى أدوات الإبداع والذكاء الاصطناعي. اختر المدة التي تناسبك، واطّلع على السعر وطريقة التفعيل قبل أن تطلب.",
    browse: "تصفّح الاشتراكات",
    how: "كيف أطلب؟",
    guest: "بدون إنشاء حساب",
    pricesDa: "أسعار بالدينار الجزائري",
    spotlight: "في الواجهة",
    available: "متوفر",
    unavailable: "غير متوفر حالياً",
    choosePlan: "اختر مدتك",
    viewOffers: "عرض العروض",
    viewDetails: "تفاصيل الاشتراك",
    snapDescription: "ضمان طيلة مدة الاشتراك.",
    checkCompatibility: "راجع توافق جهازك وشروط الخطة قبل الطلب.",
    payWith: "طرق الدفع",
    paymentDetails: "تفاصيل الدفع",
    shop: "المتجر",
    categories: "التصنيفات",
    support: "تواصل معنا",
    language: "اللغة",
    light: "الوضع الفاتح",
    dark: "الوضع الداكن",
    cart: "السلة",
    menu: "القائمة",
    skip: "انتقل إلى المحتوى",
    catalogEyebrow: "اختر ما يناسبك",
    catalogTitle: "الاشتراكات",
    catalogIntro: "قارن السعر والمدة، ثم افتح المنتج لاختيار خطتك.",
    search: "ابحث عن اشتراك",
    searchPlaceholder: "Snapchat، CapCut، Gemini…",
    all: "الكل",
    more: "عرض المزيد من الاشتراكات",
    showing: "اشتراك معروض",
    empty: "لا توجد اشتراكات في هذا القسم حالياً.",
    durationDetails: "المدة في تفاصيل العرض",
    plans: "عرض الخطط",
    catalogLink: "افتح المتجر الكامل",
    stepsEyebrow: "من الاختيار إلى التفعيل",
    stepsTitle: "كيف أطلب؟",
    stepsIntro: "راجع التفاصيل أولاً. معلومات التحويل تظهر عند إتمام الطلب.",
    steps: [
      [
        "اختر الاشتراك والمدة",
        "افتح المنتج، راجع التوافق وما يشمله العرض، ثم اختر الخطة المناسبة.",
      ],
      [
        "حوّل المبلغ وارفع الوصل",
        "اختر طريقة الدفع، اتبع معلومات التحويل وأرفق صورة واضحة لوصل الدفع.",
      ],
      [
        "نراجع الدفع ونجهّز التفعيل",
        "بعد التحقق من الدفع، نتابع تفعيل اشتراكك حسب المنتج والخطة المختارة.",
      ],
    ],
    activation:
      "يستغرق التفعيل عادةً من 15 دقيقة إلى 12 ساعة بعد التحقق من الدفع.",
    faqEyebrow: "قبل أن تطلب",
    faqTitle: "أسئلة شائعة",
    faqIntro: "هذه أهم التفاصيل حول الدفع والتفعيل والتغطية.",
    warrantyPolicy: "اقرأ سياسة الضمان والاسترجاع",
    allFaq: "كل الأسئلة الشائعة",
    questions: [
      [
        "هل أحتاج إلى حساب في الموقع؟",
        "لا، يمكنك الطلب مباشرة كضيف. اختر المنتج والخطة، ثم أدخل بيانات الطلب وارفع وصل الدفع.",
      ],
      [
        "كيف يتم الدفع؟",
        "الدفع بتحويل يدوي عبر BaridiMob أو Binance أو RedotPay. تظهر لك معلومات التحويل عند إتمام الطلب، ورفع وصل الدفع إلزامي.",
      ],
      [
        "متى وكيف أستلم الاشتراك؟",
        "نراجع الدفع أولاً، ثم نجهّز التفعيل حسب المنتج والخطة. يستغرق ذلك عادةً من 15 دقيقة إلى 12 ساعة بعد التحقق من الدفع. تفاصيل طريقة التفعيل موجودة في صفحة كل منتج.",
      ],
      [
        "هل كل الاشتراكات لها نفس الضمان؟",
        "لا، تختلف التغطية حسب المنتج والخطة. راجع مدة الضمان وشروطه في تفاصيل العرض قبل الشراء.",
      ],
      [
        "ماذا لو حدثت مشكلة مشمولة بالضمان؟",
        "إذا كانت المشكلة بسبب Tiger Store ومشمولة بالتغطية، نحاول الاستبدال أولاً. إذا تعذّر، يُحتسب الاسترجاع حسب المبلغ المدفوع والأيام المتبقية من الضمان. المشاكل الناتجة عن العميل غير مشمولة.",
      ],
    ],
    contactTitle: "حاب تتأكد قبل ما تطلب؟",
    contactBody:
      "تعرّف علينا عبر Instagram أو تواصل معنا للاستفسار عن الاشتراك المناسب لك.",
    instagram: "تواصل معنا على Instagram",
    finalTitle: "جاهز تختار اشتراكك؟",
    finalBody: "السعر، المدة والتفاصيل أمامك. ابدأ بالعرض الذي يناسبك.",
    footerNav: "روابط المتجر",
    refund: "الاسترجاع",
    privacy: "الخصوصية",
    terms: "الشروط",
    disclaimer:
      "Tiger Store مزوّد مستقل للاشتراكات الرقمية، وغير تابع رسمياً للعلامات المعروضة.",
  },
  fr: {
    metaTitle: "Vos abonnements numériques en Algérie",
    metaDescription:
      "Découvrez les abonnements Tiger Store : prix en dinars, paiement par BaridiMob, Binance ou RedotPay et étapes claires jusqu’à l’activation.",
    eyebrow: "Abonnements numériques · Algérie",
    headline: "Votre abonnement.",
    headlineAccent: "En toute clarté.",
    intro:
      "De Snapchat Plus aux outils créatifs et à l’IA. Choisissez votre durée et consultez le prix et le mode d’activation avant de commander.",
    browse: "Voir les abonnements",
    how: "Comment ça marche ?",
    guest: "Sans créer de compte",
    pricesDa: "Prix en dinars algériens",
    spotlight: "À découvrir",
    available: "Disponible",
    unavailable: "Indisponible",
    choosePlan: "Choisir ma durée",
    viewOffers: "Voir les offres",
    viewDetails: "Voir les détails",
    snapDescription: "Garantie pendant toute la durée de l’abonnement.",
    checkCompatibility:
      "Vérifiez la compatibilité et les conditions de la formule.",
    payWith: "Moyens de paiement",
    paymentDetails: "Détails du paiement",
    shop: "Boutique",
    categories: "Catégories",
    support: "Contact",
    language: "Langue",
    light: "Mode clair",
    dark: "Mode sombre",
    cart: "Panier",
    menu: "Menu",
    skip: "Aller au contenu",
    catalogEyebrow: "À vous de choisir",
    catalogTitle: "Abonnements",
    catalogIntro:
      "Comparez les prix et les durées, puis choisissez votre formule.",
    search: "Rechercher un abonnement",
    searchPlaceholder: "Snapchat, CapCut, Gemini…",
    all: "Tout",
    more: "Voir plus d’abonnements",
    showing: "abonnements affichés",
    empty: "Aucun abonnement dans cette catégorie pour le moment.",
    durationDetails: "Durée dans les détails",
    plans: "Voir les formules",
    catalogLink: "Ouvrir toute la boutique",
    stepsEyebrow: "Du choix à l’activation",
    stepsTitle: "Comment commander",
    stepsIntro:
      "Consultez d’abord les détails. Les coordonnées de transfert s’affichent à la commande.",
    steps: [
      [
        "Choisissez votre formule",
        "Ouvrez le produit, vérifiez la compatibilité et le contenu de l’offre, puis choisissez la durée.",
      ],
      [
        "Transférez et joignez le reçu",
        "Choisissez le moyen de paiement, suivez les instructions et joignez une capture lisible du reçu.",
      ],
      [
        "Nous préparons l’activation",
        "Après vérification du paiement, nous procédons à l’activation selon le produit et la formule.",
      ],
    ],
    activation:
      "L’activation prend généralement de 15 minutes à 12 heures après vérification du paiement.",
    faqEyebrow: "Avant de commander",
    faqTitle: "Questions fréquentes",
    faqIntro: "L’essentiel sur le paiement, l’activation et la garantie.",
    warrantyPolicy: "Garantie et remboursements",
    allFaq: "Toutes les questions fréquentes",
    questions: [
      [
        "Dois-je créer un compte ?",
        "Non, vous commandez en tant qu’invité. Choisissez le produit et la formule, renseignez vos coordonnées et joignez le reçu de paiement.",
      ],
      [
        "Comment payer ?",
        "Par transfert manuel via BaridiMob, Binance ou RedotPay. Les coordonnées de transfert s’affichent à la commande. Le reçu de paiement est obligatoire.",
      ],
      [
        "Quand et comment est activé mon abonnement ?",
        "Nous vérifions le paiement, puis préparons l’activation selon le produit et la formule. Comptez généralement de 15 minutes à 12 heures après vérification. Le mode d’activation est indiqué sur chaque fiche produit.",
      ],
      [
        "La garantie est-elle identique pour tous les abonnements ?",
        "Non, la couverture dépend du produit et de la formule. Consultez la durée et les conditions de garantie dans les détails avant d’acheter.",
      ],
      [
        "Que se passe-t-il en cas de problème couvert ?",
        "Pour un problème couvert causé par Tiger Store, nous tentons d’abord un remplacement. Si cela est impossible, le remboursement est calculé selon le montant payé et les jours de garantie restants. Les problèmes causés par le client sont exclus.",
      ],
    ],
    contactTitle: "Une question avant de choisir ?",
    contactBody:
      "Découvrez Tiger Store sur Instagram ou contactez-nous pour vous renseigner sur votre abonnement.",
    instagram: "Nous contacter sur Instagram",
    finalTitle: "Votre prochain abonnement ?",
    finalBody: "Le prix, la durée et les détails. Tout pour faire votre choix.",
    footerNav: "Liens de la boutique",
    refund: "Remboursements",
    privacy: "Confidentialité",
    terms: "Conditions",
    disclaimer:
      "Tiger Store est un fournisseur indépendant d’abonnements numériques, sans affiliation officielle aux marques présentées.",
  },
  en: {
    metaTitle: "Digital subscriptions in Algeria",
    metaDescription:
      "Explore Tiger Store subscriptions with prices in dinars, BaridiMob, Binance and RedotPay payments, and clear steps from ordering to activation.",
    eyebrow: "Digital subscriptions · Algeria",
    headline: "Your next subscription.",
    headlineAccent: "Made clear.",
    intro:
      "From Snapchat Plus to creative tools and AI. Choose your duration, check the price and understand activation before you order.",
    browse: "Explore subscriptions",
    how: "How do I order?",
    guest: "No account needed",
    pricesDa: "Prices in Algerian dinars",
    spotlight: "In the spotlight",
    available: "Available",
    unavailable: "Unavailable",
    choosePlan: "Choose my plan",
    viewOffers: "View offers",
    viewDetails: "View details",
    snapDescription: "Warranty for the full subscription period.",
    checkCompatibility:
      "Check device compatibility and plan conditions before ordering.",
    payWith: "Payment methods",
    paymentDetails: "Payment details",
    shop: "Shop",
    categories: "Categories",
    support: "Contact us",
    language: "Language",
    light: "Light mode",
    dark: "Dark mode",
    cart: "Cart",
    menu: "Menu",
    skip: "Skip to content",
    catalogEyebrow: "Find your fit",
    catalogTitle: "Subscriptions",
    catalogIntro:
      "Compare prices and durations, then open a product to choose your plan.",
    search: "Search subscriptions",
    searchPlaceholder: "Snapchat, CapCut, Gemini…",
    all: "All",
    more: "Show more subscriptions",
    showing: "subscriptions shown",
    empty: "No subscriptions in this category yet.",
    durationDetails: "See plan duration",
    plans: "View plans",
    catalogLink: "Open the full shop",
    stepsEyebrow: "From choosing to activating",
    stepsTitle: "How to order",
    stepsIntro:
      "Check the details first. Transfer instructions appear at checkout.",
    steps: [
      [
        "Choose your subscription",
        "Open a product, check compatibility and what’s included, then choose your plan.",
      ],
      [
        "Transfer and upload your receipt",
        "Select a payment method, follow the transfer instructions and attach a clear receipt screenshot.",
      ],
      [
        "We check and activate",
        "Once payment is verified, we prepare activation for your chosen product and plan.",
      ],
    ],
    activation:
      "Activation usually takes 15 minutes to 12 hours after payment verification.",
    faqEyebrow: "Before you order",
    faqTitle: "Common questions",
    faqIntro: "The essentials on payment, activation and warranty coverage.",
    warrantyPolicy: "Warranty and refund policy",
    allFaq: "All frequently asked questions",
    questions: [
      [
        "Do I need to create an account?",
        "No. You can order as a guest. Choose your product and plan, enter your order details and upload your payment receipt.",
      ],
      [
        "How do I pay?",
        "Pay by manual transfer through BaridiMob, Binance or RedotPay. Transfer details appear during checkout. A payment receipt is required.",
      ],
      [
        "When and how is my subscription activated?",
        "We verify payment first, then prepare activation for your product and plan. This usually takes 15 minutes to 12 hours after verification. Each product page explains its activation method.",
      ],
      [
        "Does every subscription have the same warranty?",
        "No. Coverage depends on the product and plan. Check the warranty duration and conditions in the offer details before purchasing.",
      ],
      [
        "What happens if there’s a covered problem?",
        "For a covered failure caused by Tiger Store, we try replacement first. If that is impossible, the refund is calculated from the amount paid and the remaining covered days. Customer-caused problems are excluded.",
      ],
    ],
    contactTitle: "Want to check before you buy?",
    contactBody:
      "Get to know Tiger Store on Instagram or contact us with a question about your subscription.",
    instagram: "Contact us on Instagram",
    finalTitle: "Ready to find your subscription?",
    finalBody:
      "The price, the duration and the details. Start with the plan that fits.",
    footerNav: "Store links",
    refund: "Refunds",
    privacy: "Privacy",
    terms: "Terms",
    disclaimer:
      "Tiger Store is an independent digital subscription provider and is not officially affiliated with the brands shown.",
  },
} as const;
