"use client";
import Image from "next/image";
import Link from "next/link";
import { Menu, Search, ShoppingCart, X } from "lucide-react";
import { useEffect, useState } from "react";
import { readCart } from "@/lib/cart";

const links = [{ href: "/", label: "Home" }, { href: "/shop", label: "Shop" }, { href: "/categories", label: "Categories" }, { href: "/payment-methods", label: "Payment" }, { href: "/faq", label: "FAQ" }, { href: "/contact", label: "Support" }];
export function Header() {
  const [open, setOpen] = useState(false); const [cartCount, setCartCount] = useState(0);
  useEffect(() => { const update = () => setCartCount(readCart().reduce((total, item) => total + item.quantity, 0)); update(); window.addEventListener("tiger-store-cart-updated", update); window.addEventListener("storage", update); return () => { window.removeEventListener("tiger-store-cart-updated", update); window.removeEventListener("storage", update); }; }, []);
  return <header className="sticky top-0 z-50 border-b border-[#D9D7D2] bg-white/95 backdrop-blur" dir="ltr"><div className="mx-auto flex min-h-[72px] max-w-[1440px] items-center gap-4 px-3 sm:px-5 lg:px-8"><Link href="/" className="relative h-12 w-36 shrink-0" aria-label="Tiger Store home"><Image src="/logo/tiger-store-ui.png" alt="Tiger Store" fill sizes="144px" className="object-contain object-left" priority /></Link><nav className="hidden flex-1 items-center justify-center gap-1 lg:flex" aria-label="Main navigation">{links.map((link) => <Link key={link.href} href={link.href} className="rounded-lg px-3 py-2 text-sm font-bold text-[#151515] hover:bg-[#FFF1E6] hover:text-[#C54E00]">{link.label}</Link>)}</nav><form action="/shop" className="hidden w-64 items-center rounded-xl border border-[#D9D7D2] bg-[#F6F5F2] px-2 lg:flex"><input name="q" placeholder="Search products" className="min-h-10 flex-1 bg-transparent px-2 text-sm text-[#151515] outline-none placeholder:text-[#5F6368]" /><button type="submit" className="inline-flex h-9 w-9 items-center justify-center rounded-lg text-[#151515] hover:bg-white" aria-label="Search"><Search className="h-4 w-4" /></button></form><Link href="/cart" className="relative inline-flex h-11 w-11 items-center justify-center rounded-xl border border-[#D9D7D2] text-[#151515] hover:bg-[#FFF1E6]" aria-label="Cart"><ShoppingCart className="h-5 w-5" />{cartCount > 0 && <span className="absolute -right-1 -top-1 inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-[#FF7300] px-1 text-[10px] font-black text-[#111]">{cartCount}</span>}</Link><button type="button" onClick={() => setOpen((value) => !value)} className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-[#D9D7D2] text-[#151515] lg:hidden" aria-label="Toggle menu" aria-expanded={open}>{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{open && <nav className="border-t border-[#D9D7D2] bg-white px-3 py-3 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-[1440px] gap-1">{links.map((link) => <Link key={link.href} href={link.href} onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm font-bold text-[#151515] hover:bg-[#FFF1E6]">{link.label}</Link>)}</div></nav>}</header>;
}
