"use client";

import Image from "next/image";
import Link from "next/link";
import { Menu, Moon, Search, ShoppingCart, Sun, X } from "lucide-react";
import { useEffect, useState } from "react";
import { AnnouncementStrip } from "@/components/AnnouncementStrip";
import { t } from "@/lib/i18n";
import { readCart } from "@/lib/cart";
import { useLocale } from "@/lib/useLocale";
import { ThemePreference, useTheme } from "@/lib/useTheme";

export function Header() {
  const [open, setOpen] = useState(false); const [cartCount, setCartCount] = useState(0);
  const { locale, setLocale } = useLocale(); const { theme, setTheme } = useTheme();
  useEffect(() => { const update = () => setCartCount(readCart().reduce((total, item) => total + item.quantity, 0)); update(); window.addEventListener("tiger-store-cart-updated", update); window.addEventListener("storage", update); return () => { window.removeEventListener("tiger-store-cart-updated", update); window.removeEventListener("storage", update); }; }, []);
  const links = [["/", "home"], ["/shop", "shop"], ["/categories", "categories"], ["/payment-methods", "payment"], ["/faq", "faq"], ["/contact", "support"]] as const;
  return <><header className="sticky top-0 z-50 border-b border-[var(--border-color)] bg-[var(--surface)]/95 text-[var(--text)] backdrop-blur" dir={locale === "ar" ? "rtl" : "ltr"}><div className="mx-auto flex min-h-[72px] max-w-[1440px] items-center gap-3 px-3 sm:px-5 lg:px-8"><Link href="/" className="relative h-12 w-36 shrink-0" aria-label="Tiger Store home"><Image src="/logo/tiger-store-ui.png" alt="Tiger Store" fill sizes="144px" className="object-contain object-left" priority /></Link><nav className="hidden flex-1 items-center justify-center gap-1 lg:flex" aria-label="Main navigation">{links.map(([href, key]) => <Link key={href} href={href} className="rounded-lg px-3 py-2 text-sm font-bold hover:bg-[#FFF1E6] hover:text-[#C54E00]">{t(locale, key)}</Link>)}</nav><form action="/shop" className="hidden w-56 items-center rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-2 lg:flex"><input name="q" placeholder={t(locale, "search")} className="min-h-10 flex-1 bg-transparent px-2 text-sm outline-none placeholder:text-[var(--muted-text)]" /><button type="submit" className="inline-flex h-9 w-9 items-center justify-center rounded-lg" aria-label={t(locale, "search")}><Search className="h-4 w-4" /></button></form><HeaderControls locale={locale} setLocale={setLocale} theme={theme} setTheme={setTheme} /><Link href="/cart" className="relative inline-flex h-11 w-11 items-center justify-center rounded-xl border border-[var(--border-color)]" aria-label={t(locale, "cart")}><ShoppingCart className="h-5 w-5" />{cartCount > 0 && <span className="absolute -right-1 -top-1 inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-[#FF7300] px-1 text-[10px] font-black text-[#151515]">{cartCount}</span>}</Link><button type="button" onClick={() => setOpen((value) => !value)} className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-[var(--border-color)] lg:hidden" aria-label="Toggle menu" aria-expanded={open}>{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{open && <nav className="border-t border-[var(--border-color)] bg-[var(--surface)] px-3 py-3 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto grid max-w-[1440px] gap-1">{links.map(([href, key]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm font-bold hover:bg-[#FFF1E6]">{t(locale, key)}</Link>)}<div className="mt-2"><HeaderControls locale={locale} setLocale={setLocale} theme={theme} setTheme={setTheme} mobile /></div></div></nav>}</header><AnnouncementStrip /></>;
}

function HeaderControls({ locale, setLocale, theme, setTheme, mobile = false }: { locale: ReturnType<typeof useLocale>["locale"]; setLocale: ReturnType<typeof useLocale>["setLocale"]; theme: ThemePreference; setTheme: (theme: ThemePreference) => void; mobile?: boolean }) {
  return <div className={`items-center gap-2 ${mobile ? "flex" : "hidden xl:flex"}`}><label className="sr-only" htmlFor={mobile ? "mobile-language" : "language"}>{t(locale, "language")}</label><select id={mobile ? "mobile-language" : "language"} value={locale} onChange={(event) => setLocale(event.target.value as typeof locale)} className="h-10 rounded-lg border border-[var(--border-color)] bg-[var(--page)] px-2 text-xs font-bold"><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select><label className="sr-only" htmlFor={mobile ? "mobile-theme" : "theme"}>{t(locale, "theme")}</label><select id={mobile ? "mobile-theme" : "theme"} value={theme} onChange={(event) => setTheme(event.target.value as ThemePreference)} className="h-10 rounded-lg border border-[var(--border-color)] bg-[var(--page)] px-2 text-xs font-bold"><option value="light">{t(locale, "light")}</option><option value="dark">{t(locale, "dark")}</option><option value="system">{t(locale, "system")}</option></select>{theme === "dark" ? <Moon className="h-4 w-4" aria-hidden="true" /> : <Sun className="h-4 w-4" aria-hidden="true" />}</div>;
}
