"use client";

import Image from "next/image";
import Link from "next/link";
import { Check, Clock3, Heart, ShieldCheck, ShoppingCart } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { CurrencyPrice } from "@/components/CurrencyPrice";
import { Button } from "@/components/ui/button";
import { addCartItem, createCartItem } from "@/lib/cart";
import { categorySlug } from "@/lib/categories";
import { Product, ProductPriceOption } from "@/lib/types";
import { cn } from "@/lib/utils";
import { useLocale } from "@/lib/useLocale";
import { readWishlist, toggleWishlist } from "@/lib/wishlist";
import { trackAddToCart, trackViewContent } from "@/lib/meta-pixel";

type Offer = ProductPriceOption & { key: string };
export function ProductDetails({ product }: { product: Product }) {
  const { locale } = useLocale(); const ar = locale === "ar";
  const offers = useMemo<Offer[]>(() => (product.priceOptions?.length ? product.priceOptions : [{ label: product.duration || "default", labelAr: product.durationAr || "default", price: product.price, duration: product.duration, durationAr: product.durationAr, available: product.available }]).map((item) => ({ ...item, key: item.label })), [product]);
  const [selectedKey, setSelectedKey] = useState(offers[0]?.key ?? "default"); const [added, setAdded] = useState(false); const [wishlisted, setWishlisted] = useState(false);
  const selected = offers.find((item) => item.key === selectedKey) ?? offers[0]; const unavailable = !product.available || !selected || selected.available === false;
  const details = product.details; const value = (arValue?: string, enValue?: string) => ar ? arValue : enValue;
  const labels = ar ? { home: "الرئيسية", plan: "اختر العرض", available: "متوفر", unavailable: "غير متوفر", buy: "اشتر الآن", cart: "أضف إلى السلة", added: "تمت الإضافة", wishlist: "المفضلة", description: "وصف المنتج", faq: "أسئلة شائعة", priceUnavailable: "السعر غير متوفر", productInfo: "تفاصيل العرض", duration: "المدة", activation: "طريقة التفعيل", activationTime: "وقت التفعيل", warranty: "الضمان", account: "نوع الحساب", credits: "الأرصدة", storage: "التخزين", compatibility: "توافق الأجهزة", notice: "ملاحظة مهمة", trust: "شراء واضح وآمن" } : { home: "Home", plan: "Choose an offer", available: "Available", unavailable: "Out of stock", buy: "Buy now", cart: "Add to cart", added: "Added", wishlist: "Wishlist", description: "Product description", faq: "Frequently asked questions", priceUnavailable: "Price unavailable", productInfo: "Offer details", duration: "Duration", activation: "Activation method", activationTime: "Activation time", warranty: "Warranty", account: "Account type", credits: "Included credits", storage: "Storage", compatibility: "Device compatibility", notice: "Important notice", trust: "A clear, safe purchase" };
  useEffect(() => { const update = () => setWishlisted(readWishlist().includes(product.id)); update(); window.addEventListener("tiger-store-wishlist-updated", update); return () => window.removeEventListener("tiger-store-wishlist-updated", update); }, [product.id]);
  useEffect(() => { trackViewContent({ id: product.id, name: product.name, category: product.category, price: product.price }); fetch("/api/track", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event_type: "product_view", product_id: product.id }) }).catch(() => {}); }, [product]);
  const add = () => { if (unavailable || !selected) return; addCartItem(createCartItem(product, selected)); setAdded(true); trackAddToCart({ id: product.id, name: product.name, price: selected.price, quantity: 1 }); };
  const info = [
    [labels.duration, value(selected?.durationAr, selected?.duration)], [labels.activationTime, value(details?.activationTimeAr, details?.activationTimeEn)], [labels.activation, value(details?.activationMethodAr || product.activationTypeAr, details?.activationMethodEn || product.activationTypeEn)], [labels.warranty, value(details?.warrantyAr, details?.warrantyEn)], [labels.account, value(details?.accountTypeAr, details?.accountTypeEn)], [labels.credits, value(details?.creditsAr, details?.creditsEn)], [labels.storage, value(details?.storageAr, details?.storageEn)], [labels.compatibility, value(selected?.compatibilityAr || details?.compatibilityAr, selected?.compatibilityEn || details?.compatibilityEn)],
  ].filter((item): item is [string, string] => Boolean(item[1]));
  return <section className="space-y-8" dir={ar ? "rtl" : "ltr"}>
    <nav className="text-sm font-bold text-white/60"><Link href="/" className="hover:text-tiger-gold">{labels.home}</Link><span className="mx-2">/</span><Link href={`/categories/${categorySlug(product.category)}`} className="hover:text-tiger-gold">{ar ? product.categoryAr : product.category}</Link><span className="mx-2">/</span><span className="text-white">{ar ? product.nameAr : product.name}</span></nav>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,480px)_minmax(0,1fr)_360px] xl:items-start">
      <div className="overflow-hidden rounded-md border border-white/10 bg-[#202020] shadow-[0_24px_70px_rgba(0,0,0,.36)]"><div className="relative aspect-[4/5]"><Image src={product.image} alt={`${product.name} product artwork`} fill priority sizes="(min-width:1280px) 480px, 100vw" className="object-contain p-3" />{unavailable && <span className="absolute start-4 top-4 rounded-full bg-black/85 px-3 py-1 text-xs font-black text-white">{labels.unavailable}</span>}</div></div>
      <div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-tiger-ember/10 px-3 py-1 text-xs font-black text-tiger-gold">{ar ? product.categoryAr : product.category}</span><span className={cn("rounded-full px-3 py-1 text-xs font-black", unavailable ? "bg-white/10 text-white/55" : "bg-emerald-400/10 text-emerald-300")}>{unavailable ? labels.unavailable : labels.available}</span></div><h1 className="mt-4 text-3xl font-black leading-tight text-white sm:text-5xl">{ar ? product.nameAr : product.name}</h1><p className="mt-4 max-w-2xl text-base font-semibold leading-8 text-white/75">{ar ? product.shortDescriptionAr : product.shortDescriptionEn}</p>
        {offers.length > 1 && <div className="mt-7"><h2 className="mb-3 font-black text-white">{labels.plan}</h2><div className="grid gap-3 sm:grid-cols-2">{offers.map((offer) => <button key={offer.key} type="button" disabled={offer.available === false} onClick={() => setSelectedKey(offer.key)} className={cn("min-h-24 rounded-md border p-4 text-start focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-tiger-ember disabled:opacity-45", selectedKey === offer.key ? "border-tiger-ember bg-tiger-ember/10" : "border-white/10 bg-white/[.035]")}><span className="block font-black text-white">{ar ? offer.labelAr : offer.label}</span><span className="mt-2 block font-black text-tiger-gold"><CurrencyPrice amount={offer.price} locale={locale} /></span>{(offer.compatibilityAr || offer.compatibilityEn) && <span className="mt-1 block text-xs font-bold text-white/60">{value(offer.compatibilityAr, offer.compatibilityEn)}</span>}</button>)}</div></div>}
        <div className="mt-7 grid gap-3 sm:grid-cols-2">{info.map(([label, content]) => <div key={label} className="rounded-md border border-white/10 bg-white/[.035] p-4"><p className="text-xs font-black text-tiger-gold">{label}</p><p className="mt-2 text-sm font-bold leading-6 text-white">{content}</p></div>)}</div>
        {value(details?.noticeAr, details?.noticeEn) && <div className="mt-5 rounded-md border border-tiger-ember/35 bg-tiger-ember/10 p-4 text-sm font-bold leading-7 text-white"><span className="text-tiger-gold">{labels.notice}: </span>{value(details?.noticeAr, details?.noticeEn)}</div>}
      </div>
      <aside className="premium-card h-fit rounded-md p-5 xl:sticky xl:top-24"><p className="text-xs font-black uppercase tracking-wider text-white/55">{labels.trust}</p><p className="mt-2 text-3xl font-black text-tiger-ember">{selected && selected.price > 0 ? <CurrencyPrice amount={selected.price} locale={locale} /> : labels.priceUnavailable}</p><p className="mt-4 rounded-md border border-tiger-ember/20 bg-tiger-ember/10 p-3 text-sm font-bold leading-7 text-white">{value(details?.activationTimeAr, details?.activationTimeEn) || "15 minutes–12 hours after payment"}</p><div className="mt-5 grid gap-3">{!unavailable && selected ? <Button asChild className="min-h-12 w-full rounded-full"><Link href={`/checkout?product=${encodeURIComponent(product.slug)}&option=${encodeURIComponent(selected.label)}`}>{labels.buy}</Link></Button> : <Button disabled className="min-h-12 w-full rounded-full">{labels.unavailable}</Button>}<Button type="button" disabled={unavailable} variant="secondary" className="min-h-12 w-full rounded-full" onClick={add}><ShoppingCart className="h-4 w-4" />{added ? labels.added : labels.cart}</Button></div><button type="button" onClick={() => setWishlisted(toggleWishlist(product.id).includes(product.id))} className="mt-4 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full border border-white/10 text-sm font-black text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-tiger-ember"><Heart className={cn("h-4 w-4", wishlisted && "fill-tiger-ember text-tiger-ember")} />{labels.wishlist}</button><div className="mt-5 space-y-2 text-xs font-bold leading-6 text-white/65"><p className="flex gap-2"><Clock3 className="mt-1 h-4 w-4 shrink-0 text-tiger-gold" />{value(details?.activationTimeAr, details?.activationTimeEn) || "15 minutes–12 hours after payment"}</p><p className="flex gap-2"><ShieldCheck className="mt-1 h-4 w-4 shrink-0 text-tiger-gold" />{value(details?.warrantyAr, details?.warrantyEn) || labels.trust}</p></div></aside>
    </div>
    <section className="rounded-md border border-white/10 bg-[#181818] p-5 sm:p-7"><h2 className="text-2xl font-black text-white">{labels.description}</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{(ar ? product.featuresAr : product.featuresEn).map((feature) => <li key={feature} className="flex items-center gap-3 rounded-md border border-white/8 bg-white/[.035] p-3 font-bold text-white/80"><Check className="h-4 w-4 shrink-0 text-tiger-gold" />{feature}</li>)}</ul></section>
    {product.faqs?.length ? <section className="rounded-md border border-white/10 bg-[#181818] p-5 sm:p-7"><h2 className="text-2xl font-black text-white">{labels.faq}</h2><div className="mt-5 grid gap-3">{product.faqs.map((item) => <details key={item.questionEn} className="rounded-md border border-white/10 bg-white/[.035] p-4"><summary className="cursor-pointer font-black text-white">{ar ? item.questionAr : item.questionEn}</summary><p className="mt-3 text-sm font-semibold leading-7 text-white/70">{ar ? item.answerAr : item.answerEn}</p></details>)}</div></section> : null}
  </section>;
}
