import type { Locale } from "@/lib/types";

type Key = "home" | "shop" | "categories" | "payment" | "faq" | "support" | "cart" | "search" | "language" | "theme" | "light" | "dark" | "system" | "buyNow" | "inStock" | "outOfStock" | "price" | "duration" | "compatibility" | "activationType" | "activationTime" | "warranty" | "productDetails" | "chooseDuration" | "viewAll" | "digitalSubscriptions" | "securePayment" | "whatsappSupport" | "selectedWarranty" | "activationMessage" | "menu" | "priceUnavailable" | "accountType" | "includedCredits" | "storage" | "explore" | "paymentMethods" | "contact" | "refundPolicy" | "footerDescription" | "footerDisclaimer" | "copyright" | "viewProduct" | "fromPrice" | "priceVaries" | "productArtwork" | "productFaq";

const strings: Record<Key, Record<Locale, string>> = {
  home: { en: "Home", fr: "Accueil", ar: "الرئيسية" }, shop: { en: "Shop", fr: "Boutique", ar: "المتجر" }, categories: { en: "Categories", fr: "Catégories", ar: "الأقسام" }, payment: { en: "Payment", fr: "Paiement", ar: "الدفع" }, faq: { en: "FAQ", fr: "FAQ", ar: "الأسئلة" }, support: { en: "Support", fr: "Assistance", ar: "الدعم" }, cart: { en: "Cart", fr: "Panier", ar: "السلة" }, search: { en: "Search products", fr: "Rechercher des produits", ar: "ابحث عن المنتجات" }, language: { en: "Language", fr: "Langue", ar: "اللغة" }, theme: { en: "Theme", fr: "Thème", ar: "المظهر" }, light: { en: "Light", fr: "Clair", ar: "فاتح" }, dark: { en: "Dark", fr: "Sombre", ar: "داكن" }, system: { en: "System", fr: "Système", ar: "النظام" }, buyNow: { en: "Buy Now", fr: "Acheter", ar: "اشتر الآن" }, inStock: { en: "In stock", fr: "En stock", ar: "متوفر" }, outOfStock: { en: "Out of stock", fr: "Rupture de stock", ar: "غير متوفر" }, price: { en: "Price", fr: "Prix", ar: "السعر" }, duration: { en: "Duration", fr: "Durée", ar: "المدة" }, compatibility: { en: "Device compatibility", fr: "Compatibilité", ar: "توافق الجهاز" }, activationType: { en: "Activation type", fr: "Type d’activation", ar: "نوع التفعيل" }, activationTime: { en: "Activation time", fr: "Délai d’activation", ar: "وقت التفعيل" }, warranty: { en: "Warranty", fr: "Garantie", ar: "الضمان" }, productDetails: { en: "Product details", fr: "Détails du produit", ar: "تفاصيل المنتج" }, chooseDuration: { en: "Choose duration", fr: "Choisir la durée", ar: "اختر المدة" }, viewAll: { en: "View all", fr: "Voir tout", ar: "عرض الكل" }, digitalSubscriptions: { en: "Digital subscriptions", fr: "Abonnements numériques", ar: "اشتراكات رقمية" }, securePayment: { en: "Secure payment", fr: "Paiement sécurisé", ar: "دفع آمن" }, whatsappSupport: { en: "WhatsApp support", fr: "Assistance WhatsApp", ar: "دعم عبر واتساب" }, selectedWarranty: { en: "Warranty on selected products", fr: "Garantie sur certains produits", ar: "ضمان على منتجات محددة" }, activationMessage: { en: "Usually 15 minutes–12 hours after payment verification", fr: "Généralement 15 min à 12 h après vérification du paiement", ar: "عادةً خلال 15 دقيقة إلى 12 ساعة بعد تأكيد الدفع" },
  menu: { en: "Menu", fr: "Menu", ar: "القائمة" }, priceUnavailable: { en: "Price unavailable", fr: "Prix indisponible", ar: "السعر غير متوفر" }, accountType: { en: "Account type", fr: "Type de compte", ar: "نوع الحساب" }, includedCredits: { en: "Included credits", fr: "Crédits inclus", ar: "الرصيد المشمول" }, storage: { en: "Storage", fr: "Stockage", ar: "التخزين" }, explore: { en: "Explore", fr: "Explorer", ar: "تصفح" }, paymentMethods: { en: "Payment methods", fr: "Moyens de paiement", ar: "طرق الدفع" }, contact: { en: "Contact", fr: "Contact", ar: "تواصل معنا" }, refundPolicy: { en: "Refund policy", fr: "Politique de remboursement", ar: "سياسة الاسترجاع" }, footerDescription: { en: "Digital subscriptions for AI, design, learning, and software.", fr: "Abonnements numériques pour l’IA, le design, l’apprentissage et les logiciels.", ar: "اشتراكات رقمية للذكاء الاصطناعي والتصميم والتعلّم والبرامج." }, footerDisclaimer: { en: "Tiger Store is an independent digital subscription provider and is not officially affiliated with the brands listed.", fr: "Tiger Store est un fournisseur indépendant et n’est pas affilié officiellement aux marques citées.", ar: "Tiger Store متجر مستقل للاشتراكات الرقمية ولا يمثل العلامات المذكورة رسمياً." }, copyright: { en: "© 2026 Tiger Store · tiger-storedz.com", fr: "© 2026 Tiger Store · tiger-storedz.com", ar: "© 2026 Tiger Store · tiger-storedz.com" },
  viewProduct: { en: "View product", fr: "Voir le produit", ar: "عرض المنتج" }, fromPrice: { en: "From", fr: "À partir de", ar: "من" }, priceVaries: { en: "Price depends on the selected plan.", fr: "Le prix dépend de l’offre choisie.", ar: "السعر يتغير حسب الخطة المختارة." }, productArtwork: { en: "Product artwork", fr: "Visuel du produit", ar: "صورة المنتج" }, productFaq: { en: "Frequently asked questions", fr: "Questions fréquentes", ar: "أسئلة شائعة" },
};
export function t(locale: Locale, key: Key) { return strings[key][locale]; }

export function productFaqEntries(locale: Locale, name: string, nameAr: string) {
  const isArabic = locale === "ar";
  const productName = isArabic ? nameAr : name;
  return [
    { question: isArabic ? "متى يتم التفعيل؟" : "When is activation completed?", answer: isArabic ? "يبدأ التفعيل عادة خلال 15 دقيقة إلى 12 ساعة بعد تأكيد الدفع ووصول وصل التحويل." : "Activation usually begins within 15 minutes–12 hours after payment verification and receipt upload." },
    { question: isArabic ? `كيف يتم تفعيل ${productName}؟` : `How is ${productName} activated?`, answer: isArabic ? "نطلب فقط المعلومات الضرورية للتفعيل، ثم نفعّل الخدمة بالطريقة الموضحة في تفاصيل المنتج." : "We request only the information needed for activation, then activate the service as described in the product details." },
  ];
}
