import type { Locale, Product, ProductDetails, ProductPriceOption } from "@/lib/types";

const french: Record<string, string> = {
  "1 month": "1 mois", "3 months": "3 mois", "6 months": "6 mois", "12 months": "12 mois", "18 months": "18 mois", "1 year": "1 an", "3 years": "3 ans", "Standard": "Standard",
  "Full warranty for the offer duration": "Garantie complète", "No warranty after activation": "Sans garantie après l’activation", "Activated on your personal account/email": "Activé sur votre compte ou e-mail personnel", "Your personal account": "Votre compte personnel", "Ready-made private account": "Compte privé prêt à l’emploi", "Gmail required": "Compte Gmail requis", "Gmail account required": "Compte Gmail requis", "iPhone only": "iPhone uniquement", "Android and iPhone": "Android et iPhone", "Personal activation": "Activation personnelle", "Customer account activation": "Activation sur le compte client", "Full-year warranty": "Garantie complète d’un an", "12-month duration": "Durée de 12 mois", "18-month duration": "Durée de 18 mois", "One year": "Un an", "Full warranty": "Garantie complète", "Activation on your account": "Activation sur votre compte", "Change email and password": "Modifier l’e-mail et le mot de passe", "TikTok can be connected": "TikTok peut être connecté", "600 credits monthly": "600 crédits par mois", "4,000 credits monthly": "4 000 crédits par mois", "100 credits monthly": "100 crédits par mois", "Invitation to personal email": "Invitation sur votre e-mail personnel", "Activation on your existing account": "Activation sur votre compte existant", "No password required": "Aucun mot de passe requis", "Personal email activation": "Activation sur votre e-mail personnel", "5 TB storage": "5 To de stockage", "In stock": "En stock", "Out of stock": "Rupture de stock", "This product is currently unavailable.": "Ce produit est actuellement indisponible.", "This product is currently unavailable and ordering is disabled.": "Ce produit est actuellement indisponible et la commande est désactivée.",
};
const categories = [
  { id: "all", en: "All Products", fr: "Tous les produits", ar: "كل المنتجات", matches: [] },
  { id: "ai", en: "AI Tools", fr: "Outils IA", ar: "أدوات الذكاء الاصطناعي", matches: ["AI"] },
  { id: "creative", en: "Creative Tools", fr: "Outils créatifs", ar: "أدوات إبداعية", matches: ["Design", "Video Editing"] },
  { id: "development", en: "Development", fr: "Développement", ar: "التطوير", matches: ["Developer Tools"] },
  { id: "learning", en: "Learning", fr: "Apprentissage", ar: "التعلم", matches: ["Education"] },
  { id: "software", en: "Professional Software", fr: "Logiciels professionnels", ar: "برامج احترافية", matches: ["Architecture", "Software", "VPN"] },
  { id: "social", en: "Social & Entertainment", fr: "Social et divertissement", ar: "التواصل والترفيه", matches: ["Social", "Social Media"] },
] as const;
export const productCategories = categories;
export function translateSupport(value: string | undefined, locale: Locale) { if (!value) return undefined; return locale === "fr" ? (french[value] ?? value) : value; }
export function productValue(product: Product, locale: Locale, field: "description" | "duration" | "activation" | "features") { const english = field === "description" ? product.shortDescriptionEn : field === "duration" ? product.duration : field === "activation" ? product.activationTypeEn : ""; const arabic = field === "description" ? product.shortDescriptionAr : field === "duration" ? product.durationAr : field === "activation" ? product.activationTypeAr : ""; return locale === "ar" ? arabic : translateSupport(english, locale) ?? ""; }
export function optionValue(option: ProductPriceOption, locale: Locale, field: "label" | "duration" | "compatibility") { const english = field === "label" ? option.label : field === "duration" ? option.duration : option.compatibilityEn; const arabic = field === "label" ? option.labelAr : field === "duration" ? option.durationAr : option.compatibilityAr; return locale === "ar" ? arabic : translateSupport(english, locale); }
export function detailValue(details: ProductDetails | undefined, locale: Locale, field: "activation" | "warranty" | "account" | "credits" | "storage" | "compatibility" | "notice") { if (!details) return undefined; const suffix = field === "activation" ? "activationMethod" : field === "account" ? "accountType" : field; const english = details[`${suffix}En` as keyof ProductDetails] as string | undefined; const arabic = details[`${suffix}Ar` as keyof ProductDetails] as string | undefined; return locale === "ar" ? arabic : translateSupport(english, locale); }
