-- Revocable administrator sessions, additional dashboard users, and IP bans.
-- Server-only access is enforced by RLS plus revoked anon/authenticated grants.

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique check (email = lower(email)),
  display_name text not null check (char_length(display_name) between 2 and 80),
  password_hash text not null,
  is_active boolean not null default true,
  created_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  id uuid primary key,
  admin_user_id uuid references public.admin_users(id) on delete cascade,
  admin_email text not null,
  admin_name text not null,
  is_owner boolean not null default false,
  ip_hash text not null,
  ip_encrypted text not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  revoked_reason text
);

create index if not exists admin_sessions_active_idx
  on public.admin_sessions (revoked_at, expires_at desc);
create index if not exists admin_sessions_ip_idx
  on public.admin_sessions (ip_hash, revoked_at);

create table if not exists public.admin_ip_bans (
  ip_hash text primary key,
  ip_encrypted text not null,
  reason text not null default '',
  created_by_email text not null,
  banned_at timestamptz not null default now()
);

create table if not exists public.admin_security_pin_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists admin_security_pin_attempts_window_idx
  on public.admin_security_pin_attempts (ip_hash, attempted_at desc);

alter table public.admin_users enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.admin_ip_bans enable row level security;
alter table public.admin_security_pin_attempts enable row level security;

revoke all on public.admin_users, public.admin_sessions, public.admin_ip_bans, public.admin_security_pin_attempts from anon, authenticated;
