import { notFound } from "next/navigation";
import { cookies } from "next/headers";
import { submitTelegramWarrantyAction, acknowledgeBalanceAction } from "@/app/w/[token]/actions";
import { getTelegramWarranty } from "@/lib/telegram-warranty";
import { getOrderById } from "@/lib/admin-store";
import { WarrantyForm } from "@/app/w/[token]/WarrantyForm";
export const dynamic = "force-dynamic";
export const metadata = { title: "Warranty certificate", robots: { index: false, follow: false } };
export default async function TelegramWarrantyPage({ params }: { params: Promise<{ token: string }> }) {
 const { token } = await params; const warranty = await getTelegramWarranty(token); if (!warranty) notFound(); const order = await getOrderById(warranty.order_id); const ar = (await cookies()).get("tiger-store-locale")?.value !== "en"; const item = order?.products[0]; if (!order || !item) notFound();
 const c = ar ? { title:"ضمان Snapchat", form:"أكمل بيانات الضمان", review:"راجع المعلومات جيداً: بعد التأكيد لا يمكن تعديلها.", name:"الاسم الكامل", user:"اسم المستخدم", platform:"منصة التفعيل", phone:"رقم الهاتف", email:"البريد الإلكتروني", confirm:"تأكيد وإصدار الشهادة", ready:"شهادتك جاهزة", download:"تحميل شهادة PDF", warning:"تنبيه الرصيد: تأكد من وجود الرصيد المطلوب في الحساب قبل المتابعة.", accept:"فهمت تنبيه الرصيد", platformOptions:{placeholder:"اختر المنصة",instagram:"Instagram",snapchat:"Snapchat",facebook:"Facebook"} } : { title:"Snapchat warranty", form:"Complete warranty details", review:"Review carefully: details cannot be changed after confirmation.", name:"Full name", user:"Username", platform:"Activation platform", phone:"Phone", email:"Email", confirm:"Confirm and issue certificate", ready:"Your certificate is ready", download:"Download PDF certificate", warning:"Balance warning: make sure the required balance is available before continuing.", accept:"I understand the balance warning", platformOptions:{placeholder:"Choose a platform",instagram:"Instagram",snapchat:"Snapchat",facebook:"Facebook"} };
 return <main className="store-shell min-h-screen px-4 py-8" dir={ar ? "rtl" : "ltr"}><section className="mx-auto max-w-xl rounded-3xl border border-[var(--border-color)] bg-[var(--surface)] p-6 shadow-xl"><p className="text-sm font-black text-tiger-ember">TIGER STORE</p><h1 className="mt-2 text-3xl font-black text-[var(--text)]">{warranty.customer_details_complete ? c.ready : c.form}</h1>{warranty.customer_details_complete ? <div className="mt-6 space-y-3 text-[var(--text)]"><p><b>{ar?"الطلب":"Order"}:</b> <span dir="ltr">{order.id}</span></p><p><b>{ar?"المنتج":"Product"}:</b> {ar ? item.nameAr : item.name}</p><p><b>{ar?"الخطة":"Plan"}:</b> {ar ? item.optionAr : item.option}</p><p><b>{ar?"تاريخ الانتهاء":"Expiry"}:</b> {new Intl.DateTimeFormat(ar?"ar-DZ":"en-GB",{dateStyle:"long"}).format(new Date(warranty.ends_at))}</p>{warranty.balance_warning_required && !warranty.balance_warning_acknowledged_at ? <form action={acknowledgeBalanceAction} className="rounded-2xl border border-orange-300 bg-orange-50 p-4 text-[#532600]"><p dir="rtl" lang="ar">تنبيه الرصيد: تأكد من وجود الرصيد المطلوب في الحساب قبل المتابعة.</p>{!ar ? <p className="mt-2">{c.warning}</p> : null}<input type="hidden" name="token" value={token}/><button className="mt-3 min-h-11 rounded-xl bg-[#FF7300] px-4 font-black text-black">{c.accept}</button></form> : <a className="mt-5 flex min-h-12 items-center justify-center rounded-xl bg-[#FF7300] font-black text-black" href={`/w/${token}/certificate.pdf`}>{c.download}</a>}</div> : <div className="mt-6"><WarrantyForm token={token} action={submitTelegramWarrantyAction} copy={{...c,back:ar?"رجوع":"Back",next:ar?"مراجعة المعلومات":"Review details"}}/></div>}</section></main>;
}
