"use client";
import { useState } from "react";
type Copy = { review: string; name: string; user: string; platform: string; phone: string; email: string; confirm: string; back: string; next: string; platformOptions: { instagram: string; snapchat: string; facebook: string; placeholder: string } };

export function WarrantyForm({ token, copy, action }: { token: string; copy: Copy; action: (formData: FormData) => void | Promise<void> }) {
  const [review, setReview] = useState(false);
  const [values, setValues] = useState({ name: "", username: "", platform: "", phone: "", email: "" });
  const fields: [Exclude<keyof typeof values, "platform">, string, string][] = [["name", copy.name, "text"], ["username", copy.user, "text"], ["phone", copy.phone, "tel"], ["email", copy.email, "email"]];
  const reviewFields: [keyof typeof values, string][] = [["name", copy.name], ["username", copy.user], ["platform", copy.platform], ["phone", copy.phone], ["email", copy.email]];

  if (review) return <form action={action} className="grid gap-4"><input type="hidden" name="token" value={token} /><p className="rounded-xl bg-[var(--page)] p-3 text-sm text-[var(--muted-text)]">{copy.review}</p>{reviewFields.map(([key, label]) => <div key={key} className="rounded-xl border border-[var(--border-color)] p-3"><b>{label}</b><p>{values[key]}</p><input type="hidden" name={key} value={values[key]} /></div>)}<button type="button" onClick={() => setReview(false)} className="min-h-11 rounded-xl border border-[var(--border-color)] font-black text-[var(--text)]">{copy.back}</button><button className="min-h-12 rounded-xl bg-[#FF7300] font-black text-black">{copy.confirm}</button></form>;

  return <div className="grid gap-4">{fields.slice(0, 2).map(([key, label, type]) => <label key={key} className="grid gap-1 font-bold text-[var(--text)]">{label}<input required type={type} value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} className="min-h-12 rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-3" /></label>)}<label className="grid gap-1 font-bold text-[var(--text)]">{copy.platform}<select required value={values.platform} onChange={(event) => setValues({ ...values, platform: event.target.value })} className="min-h-12 rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-3"><option value="" disabled>{copy.platformOptions.placeholder}</option><option value="Instagram">Instagram</option><option value="Snapchat">Snapchat</option><option value="Facebook">Facebook</option></select></label>{fields.slice(2).map(([key, label, type]) => <label key={key} className="grid gap-1 font-bold text-[var(--text)]">{label}<input required type={type} value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} className="min-h-12 rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-3" /></label>)}<button type="button" onClick={() => setReview(true)} disabled={Object.values(values).some((value) => !value.trim())} className="min-h-12 rounded-xl bg-[#FF7300] font-black text-black disabled:opacity-50">{copy.next}</button></div>;
}
