"use client";
import { useState } from "react";
type Copy = { review: string; name: string; user: string; platform: string; phone: string; email: string; paymentMethod: string; confirm: string; back: string; next: string; platformOptions: { instagram: string; snapchat: string; facebook: string; placeholder: string }; paymentOptions: { placeholder: string; baridiMob: string; binance: string; redotPay: string; flexy: string } };

export function WarrantyForm({ token, copy, action }: { token: string; copy: Copy; action: (formData: FormData) => void | Promise<void> }) {
  const [review, setReview] = useState(false);
  const [values, setValues] = useState({ name: "", username: "", platform: "", phone: "", email: "", paymentMethod: "" });
  const fields: [Exclude<keyof typeof values, "platform">, string, string, boolean][] = [["name", copy.name, "text", true], ["username", copy.user, "text", true], ["phone", copy.phone, "tel", true], ["email", copy.email, "email", false]];
  const reviewFields: [keyof typeof values, string][] = [["name", copy.name], ["username", copy.user], ["platform", copy.platform], ["phone", copy.phone], ["paymentMethod", copy.paymentMethod], ["email", copy.email]];
  const requiredValuesComplete = Boolean(values.name.trim() && values.username.trim() && values.platform && values.phone.trim() && values.paymentMethod);

  if (review) return <form action={action} className="grid gap-4"><input type="hidden" name="token" value={token} /><p className="rounded-xl bg-[var(--page)] p-3 text-sm text-[var(--muted-text)]">{copy.review}</p>{reviewFields.map(([key, label]) => <div key={key} className="rounded-xl border border-[var(--border-color)] p-3"><b>{label}</b><p>{values[key]}</p><input type="hidden" name={key} value={values[key]} /></div>)}<button type="button" onClick={() => setReview(false)} className="min-h-11 rounded-xl border border-[var(--border-color)] font-black text-[var(--text)]">{copy.back}</button><button className="min-h-12 rounded-xl bg-[#FF7300] font-black text-black">{copy.confirm}</button></form>;

  return <div className="grid gap-4">{fields.slice(0, 2).map(([key, label, type, required]) => <label key={key} className="grid gap-1 font-bold text-[var(--text)]">{label}<input required={required} type={type} value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} className="min-h-12 rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-3" /></label>)}<label className="grid gap-1 font-bold text-[var(--text)]">{copy.platform}<select required value={values.platform} onChange={(event) => setValues({ ...values, platform: event.target.value })} className="min-h-12 rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-3"><option value="" disabled>{copy.platformOptions.placeholder}</option><option value="Instagram">Instagram</option><option value="Snapchat">Snapchat</option><option value="Facebook">Facebook</option></select></label><label className="grid gap-1 font-bold text-[var(--text)]">{copy.paymentMethod}<select required value={values.paymentMethod} onChange={(event) => setValues({ ...values, paymentMethod: event.target.value })} className="min-h-12 rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-3"><option value="" disabled>{copy.paymentOptions.placeholder}</option><option value="BaridiMob">{copy.paymentOptions.baridiMob}</option><option value="Binance">{copy.paymentOptions.binance}</option><option value="RedotPay">{copy.paymentOptions.redotPay}</option><option value="Flexy">{copy.paymentOptions.flexy}</option></select></label>{fields.slice(2).map(([key, label, type, required]) => <label key={key} className="grid gap-1 font-bold text-[var(--text)]">{label}<input required={required} type={type} value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} className="min-h-12 rounded-xl border border-[var(--border-color)] bg-[var(--page)] px-3" /></label>)}<button type="button" onClick={() => setReview(true)} disabled={!requiredValuesComplete} className="min-h-12 rounded-xl bg-[#FF7300] font-black text-black disabled:opacity-50">{copy.next}</button></div>;
}
